name: fission
version: '2.8.0.0'
category: API
author:
  - Brooklyn Zelenka
  - Daniel Holmgren
  - Steven Vandevelde
maintainer:
  - brooklyn@fission.codes
  - daniel@fission.codes
  - steven@fission.codes
copyright: © 2020 Fission Internet Software Services for Open Networks Inc.
license: AGPL-3.0-or-later
license-file: LICENSE
github: fission-suite/fission
tested-with: GHC==8.8.3
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  # Warn about too little
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  # Warn about too much
  - -Wredundant-constraints
  # Prettier Development
  - -fhide-source-paths

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DuplicateRecordFields
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - LiberalTypeSynonyms
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NumericUnderscores
  - OverloadedStrings
  - OverloadedLabels
  - OverloadedLists
  - PostfixOperators
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - TemplateHaskell
  - TypeOperators
  - ViewPatterns

dependencies:
  - aeson
  - aeson-casing
  - amazonka
  - amazonka-core
  - amazonka-route53
  - ansi-terminal
  - asn1-encoding
  - asn1-types
  - base
  - base58string
  - base64-bytestring
  - binary
  - bcrypt
  - bytestring
  - cryptonite
  - cryptostore
  - data-default-class
  - data-has
  - dns
  - envy
  - esqueleto
  - exceptions
  - file-embed
  - filepath
  - flow
  - fsnotify
  - generic-lens
  - Glob
  - haskeline
  - http-client
  - http-client-tls
  - http-media
  - http-types
  - ipfs
  - lens
  - lens-aeson
  - memory
  - mime-types
  - monad-logger
  - monad-time
  - mtl
  - network-uri
  - optparse-applicative
  - optparse-simple
  - parallel
  - path-pieces
  - pem
  - persistent
  - persistent-postgresql
  - persistent-template
  - pretty-simple
  - QuickCheck
  - quickcheck-instances
  - random-bytestring
  - resource-pool
  - regex-compat
  - rescue
  - rio
  - rio-orphans
  - RSA
  - scientific
  - servant
  - servant-auth-server
  - servant-auth-swagger
  - servant-client
  - servant-client-core
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - servant-swagger-ui-redoc
  - streaming-commons
  - swagger2
  - text
  - text-time
  - time
  - transformers
  - unliftio
  - uuid
  - uuid-types
  - wai
  - wai-cors
  - wai-extra
  - wai-logger
  - warp
  - warp-tls
  - word8
  - world-peace
  - utf8-string
  - vault
  - vector
  - x509
  - yaml

library:
  source-dirs: library

executables:
  fission-server:
    main: Main.hs
    source-dirs: server
    dependencies:
      - fission
      - raven-haskell
      - wai-logger
    ghc-options:
      - -threaded
      - -flate-specialise
      - -rtsopts
      - -with-rtsopts=-N
      - -with-rtsopts=-T
      - -optc-ffast-math
      - -optc-O3
      - -O2

  fission-cli:
    main: Main.hs
    source-dirs: cli
    dependencies:
      - fission
      - wai-logger
    ghc-options:
      - -threaded
      - -flate-specialise
      - -rtsopts
      - -with-rtsopts=-N
      - -with-rtsopts=-T
      - -optc-ffast-math
      - -optc-O3
      - -O2
    # uncomment to build a static binary on Linux
    # cc-options: -static
    # ld-options: -static -pthread

tests:
  fission-doctest:
    main: Main.hs
    source-dirs: doctest
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - directory
      - directory-tree
      - doctest
      - Glob
      - lens-aeson
      - yaml

  fission-test:
    main: Main.hs
    source-dirs:
      - library
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - hspec-core
      - hspec-expectations
      - hspec-wai
      - hspec-wai-json
      - fission
      - QuickCheck
      - quickcheck-instances
      - servant-quickcheck
      - tasty
      - tasty-hunit
      - tasty-hspec
      - tasty-smallcheck
      - tasty-rerun
      - transformers

  fission-lint:
    main: Main.hs
    source-dirs: lint
    dependencies:
      - base
      - hlint
      - rio

benchmarks:
  fission-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - criterion
      - fission
