name: ipfs-api
version: '0.0.1.0'
category: API
author: Brooklyn Zelenka
maintainer: hello@brooklynzelenka.com
copyright: © 2019 Brooklyn Zelenka
license: Apache-2.0
license-file: LICENSE
github: fission-suite/ipfs-api
tested-with: GHC==8.6.3
extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  - -Wall
  # as recommended in:
  # https://functor.tokyo/blog/2017-07-28-ghc-warnings-you-should-enable
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates

dependencies:
  - aeson
  - base
  - bytestring
  - data-has
  - ekg-wai
  - envy
  - etc
  - lens
  - monad-logger
  - rio
  - servant
  - servant-auth-server
  - servant-client
  - servant-server
  - servant-multipart
  - text
  - typed-process
  - wai
  - wai-extra
  - wai-logger
  - warp

library:
  source-dirs: src

executables:
  cli:
    main: Main.hs
    source-dirs: cli
    dependencies:
      - ipfs-api
      - wai-cli
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2

  server:
    main: Main.hs
    source-dirs: app
    dependencies:
      - ipfs-api
      - wai-logger
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -with-rtsopts=-T
      - -O2

tests:
  fission-doctest:
    main: Main.hs
    source-dirs: test/doctest
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - doctest
      - Glob
      - QuickCheck
      - ipfs-api

  fission-test:
    main: Main.hs
    source-dirs:
      - src
      - test
      - test/testsuite
    ghc-options:
      - -fhpc
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - hspec
      - hspec-wai
      - hspec-wai-json
      - ipfs-api
      - tasty
      - tasty-hunit
      - tasty-hspec
      - tasty-smallcheck
      - tasty-rerun
      - transformers

  fission-docs:
    main: Main.hs
    source-dirs: test/docs
    dependencies:
      - doctest
      - ipfs-api
      - process
      - regex-compat

  fission-coverage:
    main: Main.hs
    source-dirs: test/coverage
    ghc-options:
      - -fhpc
    dependencies:
      - base
      - ipfs-api
      - process
      - regex-compat

  fission-lint:
    main: Main.hs
    source-dirs: test/lint
    dependencies:
      - base
      - hlint
      - rio

benchmarks:
  fission-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - criterion
      - ipfs-api
