resolver: lts-16.23

packages:
  - fission-cli
  - fission-core

extra-deps:
  - alex-3.2.5
  - cryptostore-0.2.1.0
  - happy-1.20.0
  - hfsevents-0.1.6
  - ipfs-1.1.5.1
  - lzma-clib-5.2.2
  - raven-haskell-0.1.4.0
  - rescue-0.2.1 # FIXME explore 0.3.0, or switch to checked-exceptions
  - text-time-0.3.1

  # For ip-1.7.2
  - ip-1.7.2
  - bytebuild-0.3.6.0
  - byteslice-0.2.4.0
  - bytesmith-0.3.7.0
  - contiguous-0.5.1
  - natural-arithmetic-0.1.2.0
  - primitive-offset-0.2.0.0
  - primitive-unlifted-0.1.3.0
  - run-st-0.1.1.0
  - tuples-0.1.0.0

nix:
  enable: true
  packages:
    - lzma
    - postgresql
    - zlib
