resolver: lts-17.6

allow-newer: true

packages:
  - fission-cli
  - fission-core
  - fission-web-api
  - fission-web-client
  - fission-web-server

extra-deps:
  - amazonka-1.6.1
  - constraints-deriving-1.1.1.1
  - cryptostore-0.2.1.0
  - dimensions-2.1.0.0
  - hfsevents-0.1.6
  - ipfs-1.3.0.3
  - lzma-clib-5.2.2
  - raven-haskell-0.1.4.0
  - rescue-0.4.2.1
  - servant-auth-0.4.0.0
  - servant-auth-server-0.4.6.0
  - servant-auth-swagger-0.2.10.1
  - servant-swagger-ui-redoc-0.3.3.1.22.3
  - servant-websockets-2.0.0
  - unliftio-core-0.1.2.0

nix:
  enable:     false
  pure:       true
  shell-file: shell.nix
