resolver: lts-15.10


packages:
- .

allow-newer: true

extra-deps:
- alex-3.2.5
- base64-bytestring-1.1.0.0
- cryptostore-0.2.1.0
- happy-1.19.12
- hspec-wai-json-0.10.1
- ipfs-1.1.1
- lzma-clib-5.2.2
- raven-haskell-0.1.4.0
- servant-quickcheck-0.0.7.4
- tasty-rerun-1.1.17
- text-time-0.2.0

nix:
  enable: true
  packages:
  - lzma
  - zlib
