/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package fission-2.4.0 */
#ifndef VERSION_fission
#define VERSION_fission "2.4.0"
#endif /* VERSION_fission */
#ifndef MIN_VERSION_fission
#define MIN_VERSION_fission(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  4 || \
  (major1) == 2 && (major2) == 4 && (minor) <= 0)
#endif /* MIN_VERSION_fission */

/* package Glob-0.10.0 */
#ifndef VERSION_Glob
#define VERSION_Glob "0.10.0"
#endif /* VERSION_Glob */
#ifndef MIN_VERSION_Glob
#define MIN_VERSION_Glob(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_Glob */

/* package QuickCheck-2.13.2 */
#ifndef VERSION_QuickCheck
#define VERSION_QuickCheck "2.13.2"
#endif /* VERSION_QuickCheck */
#ifndef MIN_VERSION_QuickCheck
#define MIN_VERSION_QuickCheck(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  13 || \
  (major1) == 2 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_QuickCheck */

/* package RSA-2.4.1 */
#ifndef VERSION_RSA
#define VERSION_RSA "2.4.1"
#endif /* VERSION_RSA */
#ifndef MIN_VERSION_RSA
#define MIN_VERSION_RSA(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  4 || \
  (major1) == 2 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_RSA */

/* package aeson-1.4.7.1 */
#ifndef VERSION_aeson
#define VERSION_aeson "1.4.7.1"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 7)
#endif /* MIN_VERSION_aeson */

/* package aeson-casing-0.2.0.0 */
#ifndef VERSION_aeson_casing
#define VERSION_aeson_casing "0.2.0.0"
#endif /* VERSION_aeson_casing */
#ifndef MIN_VERSION_aeson_casing
#define MIN_VERSION_aeson_casing(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_aeson_casing */

/* package amazonka-1.6.1 */
#ifndef VERSION_amazonka
#define VERSION_amazonka "1.6.1"
#endif /* VERSION_amazonka */
#ifndef MIN_VERSION_amazonka
#define MIN_VERSION_amazonka(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_amazonka */

/* package amazonka-core-1.6.1 */
#ifndef VERSION_amazonka_core
#define VERSION_amazonka_core "1.6.1"
#endif /* VERSION_amazonka_core */
#ifndef MIN_VERSION_amazonka_core
#define MIN_VERSION_amazonka_core(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_amazonka_core */

/* package amazonka-route53-1.6.1 */
#ifndef VERSION_amazonka_route53
#define VERSION_amazonka_route53 "1.6.1"
#endif /* VERSION_amazonka_route53 */
#ifndef MIN_VERSION_amazonka_route53
#define MIN_VERSION_amazonka_route53(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_amazonka_route53 */

/* package ansi-terminal-0.10.3 */
#ifndef VERSION_ansi_terminal
#define VERSION_ansi_terminal "0.10.3"
#endif /* VERSION_ansi_terminal */
#ifndef MIN_VERSION_ansi_terminal
#define MIN_VERSION_ansi_terminal(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_VERSION_ansi_terminal */

/* package asn1-encoding-0.9.6 */
#ifndef VERSION_asn1_encoding
#define VERSION_asn1_encoding "0.9.6"
#endif /* VERSION_asn1_encoding */
#ifndef MIN_VERSION_asn1_encoding
#define MIN_VERSION_asn1_encoding(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 6)
#endif /* MIN_VERSION_asn1_encoding */

/* package asn1-types-0.3.4 */
#ifndef VERSION_asn1_types
#define VERSION_asn1_types "0.3.4"
#endif /* VERSION_asn1_types */
#ifndef MIN_VERSION_asn1_types
#define MIN_VERSION_asn1_types(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_asn1_types */

/* package base-4.13.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.13.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  13 || \
  (major1) == 4 && (major2) == 13 && (minor) <= 0)
#endif /* MIN_VERSION_base */

/* package base58string-0.10.0 */
#ifndef VERSION_base58string
#define VERSION_base58string "0.10.0"
#endif /* VERSION_base58string */
#ifndef MIN_VERSION_base58string
#define MIN_VERSION_base58string(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_base58string */

/* package base64-bytestring-1.1.0.0 */
#ifndef VERSION_base64_bytestring
#define VERSION_base64_bytestring "1.1.0.0"
#endif /* VERSION_base64_bytestring */
#ifndef MIN_VERSION_base64_bytestring
#define MIN_VERSION_base64_bytestring(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_base64_bytestring */

/* package bcrypt-0.0.11 */
#ifndef VERSION_bcrypt
#define VERSION_bcrypt "0.0.11"
#endif /* VERSION_bcrypt */
#ifndef MIN_VERSION_bcrypt
#define MIN_VERSION_bcrypt(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 11)
#endif /* MIN_VERSION_bcrypt */

/* package binary-0.8.7.0 */
#ifndef VERSION_binary
#define VERSION_binary "0.8.7.0"
#endif /* VERSION_binary */
#ifndef MIN_VERSION_binary
#define MIN_VERSION_binary(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 7)
#endif /* MIN_VERSION_binary */

/* package bytestring-0.10.10.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.10.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 10)
#endif /* MIN_VERSION_bytestring */

/* package cryptonite-0.26 */
#ifndef VERSION_cryptonite
#define VERSION_cryptonite "0.26"
#endif /* VERSION_cryptonite */
#ifndef MIN_VERSION_cryptonite
#define MIN_VERSION_cryptonite(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  26 || \
  (major1) == 0 && (major2) == 26 && (minor) <= 0)
#endif /* MIN_VERSION_cryptonite */

/* package cryptostore-0.2.1.0 */
#ifndef VERSION_cryptostore
#define VERSION_cryptostore "0.2.1.0"
#endif /* VERSION_cryptostore */
#ifndef MIN_VERSION_cryptostore
#define MIN_VERSION_cryptostore(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_cryptostore */

/* package data-default-class-0.1.2.0 */
#ifndef VERSION_data_default_class
#define VERSION_data_default_class "0.1.2.0"
#endif /* VERSION_data_default_class */
#ifndef MIN_VERSION_data_default_class
#define MIN_VERSION_data_default_class(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 2)
#endif /* MIN_VERSION_data_default_class */

/* package data-has-0.3.0.0 */
#ifndef VERSION_data_has
#define VERSION_data_has "0.3.0.0"
#endif /* VERSION_data_has */
#ifndef MIN_VERSION_data_has
#define MIN_VERSION_data_has(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_data_has */

/* package dns-4.0.1 */
#ifndef VERSION_dns
#define VERSION_dns "4.0.1"
#endif /* VERSION_dns */
#ifndef MIN_VERSION_dns
#define MIN_VERSION_dns(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  0 || \
  (major1) == 4 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_dns */

/* package envy-2.1.0.0 */
#ifndef VERSION_envy
#define VERSION_envy "2.1.0.0"
#endif /* VERSION_envy */
#ifndef MIN_VERSION_envy
#define MIN_VERSION_envy(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_envy */

/* package esqueleto-3.3.3.0 */
#ifndef VERSION_esqueleto
#define VERSION_esqueleto "3.3.3.0"
#endif /* VERSION_esqueleto */
#ifndef MIN_VERSION_esqueleto
#define MIN_VERSION_esqueleto(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  3 || \
  (major1) == 3 && (major2) == 3 && (minor) <= 3)
#endif /* MIN_VERSION_esqueleto */

/* package exceptions-0.10.4 */
#ifndef VERSION_exceptions
#define VERSION_exceptions "0.10.4"
#endif /* VERSION_exceptions */
#ifndef MIN_VERSION_exceptions
#define MIN_VERSION_exceptions(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 4)
#endif /* MIN_VERSION_exceptions */

/* package file-embed-0.0.11.2 */
#ifndef VERSION_file_embed
#define VERSION_file_embed "0.0.11.2"
#endif /* VERSION_file_embed */
#ifndef MIN_VERSION_file_embed
#define MIN_VERSION_file_embed(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 11)
#endif /* MIN_VERSION_file_embed */

/* package filepath-1.4.2.1 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.2.1"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_filepath */

/* package flow-1.0.20 */
#ifndef VERSION_flow
#define VERSION_flow "1.0.20"
#endif /* VERSION_flow */
#ifndef MIN_VERSION_flow
#define MIN_VERSION_flow(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 20)
#endif /* MIN_VERSION_flow */

/* package fsnotify-0.3.0.1 */
#ifndef VERSION_fsnotify
#define VERSION_fsnotify "0.3.0.1"
#endif /* VERSION_fsnotify */
#ifndef MIN_VERSION_fsnotify
#define MIN_VERSION_fsnotify(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_fsnotify */

/* package haskeline-0.7.5.0 */
#ifndef VERSION_haskeline
#define VERSION_haskeline "0.7.5.0"
#endif /* VERSION_haskeline */
#ifndef MIN_VERSION_haskeline
#define MIN_VERSION_haskeline(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 5)
#endif /* MIN_VERSION_haskeline */

/* package http-client-0.6.4.1 */
#ifndef VERSION_http_client
#define VERSION_http_client "0.6.4.1"
#endif /* VERSION_http_client */
#ifndef MIN_VERSION_http_client
#define MIN_VERSION_http_client(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 4)
#endif /* MIN_VERSION_http_client */

/* package http-client-tls-0.3.5.3 */
#ifndef VERSION_http_client_tls
#define VERSION_http_client_tls "0.3.5.3"
#endif /* VERSION_http_client_tls */
#ifndef MIN_VERSION_http_client_tls
#define MIN_VERSION_http_client_tls(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 5)
#endif /* MIN_VERSION_http_client_tls */

/* package http-media-0.8.0.0 */
#ifndef VERSION_http_media
#define VERSION_http_media "0.8.0.0"
#endif /* VERSION_http_media */
#ifndef MIN_VERSION_http_media
#define MIN_VERSION_http_media(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_http_media */

/* package http-types-0.12.3 */
#ifndef VERSION_http_types
#define VERSION_http_types "0.12.3"
#endif /* VERSION_http_types */
#ifndef MIN_VERSION_http_types
#define MIN_VERSION_http_types(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 3)
#endif /* MIN_VERSION_http_types */

/* package ipfs-1.0.2 */
#ifndef VERSION_ipfs
#define VERSION_ipfs "1.0.2"
#endif /* VERSION_ipfs */
#ifndef MIN_VERSION_ipfs
#define MIN_VERSION_ipfs(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_ipfs */

/* package lens-4.18.1 */
#ifndef VERSION_lens
#define VERSION_lens "4.18.1"
#endif /* VERSION_lens */
#ifndef MIN_VERSION_lens
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  18 || \
  (major1) == 4 && (major2) == 18 && (minor) <= 1)
#endif /* MIN_VERSION_lens */

/* package lens-aeson-1.1 */
#ifndef VERSION_lens_aeson
#define VERSION_lens_aeson "1.1"
#endif /* VERSION_lens_aeson */
#ifndef MIN_VERSION_lens_aeson
#define MIN_VERSION_lens_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_lens_aeson */

/* package memory-0.15.0 */
#ifndef VERSION_memory
#define VERSION_memory "0.15.0"
#endif /* VERSION_memory */
#ifndef MIN_VERSION_memory
#define MIN_VERSION_memory(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  15 || \
  (major1) == 0 && (major2) == 15 && (minor) <= 0)
#endif /* MIN_VERSION_memory */

/* package mime-types-0.1.0.9 */
#ifndef VERSION_mime_types
#define VERSION_mime_types "0.1.0.9"
#endif /* VERSION_mime_types */
#ifndef MIN_VERSION_mime_types
#define MIN_VERSION_mime_types(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_mime_types */

/* package monad-logger-0.3.32 */
#ifndef VERSION_monad_logger
#define VERSION_monad_logger "0.3.32"
#endif /* VERSION_monad_logger */
#ifndef MIN_VERSION_monad_logger
#define MIN_VERSION_monad_logger(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 32)
#endif /* MIN_VERSION_monad_logger */

/* package monad-time-0.3.1.0 */
#ifndef VERSION_monad_time
#define VERSION_monad_time "0.3.1.0"
#endif /* VERSION_monad_time */
#ifndef MIN_VERSION_monad_time
#define MIN_VERSION_monad_time(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_monad_time */

/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */

/* package network-uri-2.6.3.0 */
#ifndef VERSION_network_uri
#define VERSION_network_uri "2.6.3.0"
#endif /* VERSION_network_uri */
#ifndef MIN_VERSION_network_uri
#define MIN_VERSION_network_uri(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  6 || \
  (major1) == 2 && (major2) == 6 && (minor) <= 3)
#endif /* MIN_VERSION_network_uri */

/* package optparse-applicative-0.15.1.0 */
#ifndef VERSION_optparse_applicative
#define VERSION_optparse_applicative "0.15.1.0"
#endif /* VERSION_optparse_applicative */
#ifndef MIN_VERSION_optparse_applicative
#define MIN_VERSION_optparse_applicative(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  15 || \
  (major1) == 0 && (major2) == 15 && (minor) <= 1)
#endif /* MIN_VERSION_optparse_applicative */

/* package optparse-simple-0.1.1.2 */
#ifndef VERSION_optparse_simple
#define VERSION_optparse_simple "0.1.1.2"
#endif /* VERSION_optparse_simple */
#ifndef MIN_VERSION_optparse_simple
#define MIN_VERSION_optparse_simple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_optparse_simple */

/* package path-pieces-0.2.1 */
#ifndef VERSION_path_pieces
#define VERSION_path_pieces "0.2.1"
#endif /* VERSION_path_pieces */
#ifndef MIN_VERSION_path_pieces
#define MIN_VERSION_path_pieces(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_path_pieces */

/* package pem-0.2.4 */
#ifndef VERSION_pem
#define VERSION_pem "0.2.4"
#endif /* VERSION_pem */
#ifndef MIN_VERSION_pem
#define MIN_VERSION_pem(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_pem */

/* package persistent-2.10.5.2 */
#ifndef VERSION_persistent
#define VERSION_persistent "2.10.5.2"
#endif /* VERSION_persistent */
#ifndef MIN_VERSION_persistent
#define MIN_VERSION_persistent(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  10 || \
  (major1) == 2 && (major2) == 10 && (minor) <= 5)
#endif /* MIN_VERSION_persistent */

/* package persistent-postgresql-2.10.1.2 */
#ifndef VERSION_persistent_postgresql
#define VERSION_persistent_postgresql "2.10.1.2"
#endif /* VERSION_persistent_postgresql */
#ifndef MIN_VERSION_persistent_postgresql
#define MIN_VERSION_persistent_postgresql(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  10 || \
  (major1) == 2 && (major2) == 10 && (minor) <= 1)
#endif /* MIN_VERSION_persistent_postgresql */

/* package persistent-template-2.8.2.3 */
#ifndef VERSION_persistent_template
#define VERSION_persistent_template "2.8.2.3"
#endif /* VERSION_persistent_template */
#ifndef MIN_VERSION_persistent_template
#define MIN_VERSION_persistent_template(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  8 || \
  (major1) == 2 && (major2) == 8 && (minor) <= 2)
#endif /* MIN_VERSION_persistent_template */

/* package pretty-simple-3.2.2.0 */
#ifndef VERSION_pretty_simple
#define VERSION_pretty_simple "3.2.2.0"
#endif /* VERSION_pretty_simple */
#ifndef MIN_VERSION_pretty_simple
#define MIN_VERSION_pretty_simple(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_pretty_simple */

/* package quickcheck-instances-0.3.22 */
#ifndef VERSION_quickcheck_instances
#define VERSION_quickcheck_instances "0.3.22"
#endif /* VERSION_quickcheck_instances */
#ifndef MIN_VERSION_quickcheck_instances
#define MIN_VERSION_quickcheck_instances(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 22)
#endif /* MIN_VERSION_quickcheck_instances */

/* package random-bytestring-0.1.3.2 */
#ifndef VERSION_random_bytestring
#define VERSION_random_bytestring "0.1.3.2"
#endif /* VERSION_random_bytestring */
#ifndef MIN_VERSION_random_bytestring
#define MIN_VERSION_random_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_random_bytestring */

/* package regex-compat-0.95.2.0 */
#ifndef VERSION_regex_compat
#define VERSION_regex_compat "0.95.2.0"
#endif /* VERSION_regex_compat */
#ifndef MIN_VERSION_regex_compat
#define MIN_VERSION_regex_compat(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  95 || \
  (major1) == 0 && (major2) == 95 && (minor) <= 2)
#endif /* MIN_VERSION_regex_compat */

/* package resource-pool-0.2.3.2 */
#ifndef VERSION_resource_pool
#define VERSION_resource_pool "0.2.3.2"
#endif /* VERSION_resource_pool */
#ifndef MIN_VERSION_resource_pool
#define MIN_VERSION_resource_pool(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_resource_pool */

/* package rio-0.1.15.0 */
#ifndef VERSION_rio
#define VERSION_rio "0.1.15.0"
#endif /* VERSION_rio */
#ifndef MIN_VERSION_rio
#define MIN_VERSION_rio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 15)
#endif /* MIN_VERSION_rio */

/* package rio-orphans-0.1.1.0 */
#ifndef VERSION_rio_orphans
#define VERSION_rio_orphans "0.1.1.0"
#endif /* VERSION_rio_orphans */
#ifndef MIN_VERSION_rio_orphans
#define MIN_VERSION_rio_orphans(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_rio_orphans */

/* package scientific-0.3.6.2 */
#ifndef VERSION_scientific
#define VERSION_scientific "0.3.6.2"
#endif /* VERSION_scientific */
#ifndef MIN_VERSION_scientific
#define MIN_VERSION_scientific(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_scientific */

/* package servant-0.16.2 */
#ifndef VERSION_servant
#define VERSION_servant "0.16.2"
#endif /* VERSION_servant */
#ifndef MIN_VERSION_servant
#define MIN_VERSION_servant(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  16 || \
  (major1) == 0 && (major2) == 16 && (minor) <= 2)
#endif /* MIN_VERSION_servant */

/* package servant-auth-server-0.4.5.1 */
#ifndef VERSION_servant_auth_server
#define VERSION_servant_auth_server "0.4.5.1"
#endif /* VERSION_servant_auth_server */
#ifndef MIN_VERSION_servant_auth_server
#define MIN_VERSION_servant_auth_server(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 5)
#endif /* MIN_VERSION_servant_auth_server */

/* package servant-auth-swagger-0.2.10.0 */
#ifndef VERSION_servant_auth_swagger
#define VERSION_servant_auth_swagger "0.2.10.0"
#endif /* VERSION_servant_auth_swagger */
#ifndef MIN_VERSION_servant_auth_swagger
#define MIN_VERSION_servant_auth_swagger(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 10)
#endif /* MIN_VERSION_servant_auth_swagger */

/* package servant-client-0.16.0.1 */
#ifndef VERSION_servant_client
#define VERSION_servant_client "0.16.0.1"
#endif /* VERSION_servant_client */
#ifndef MIN_VERSION_servant_client
#define MIN_VERSION_servant_client(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  16 || \
  (major1) == 0 && (major2) == 16 && (minor) <= 0)
#endif /* MIN_VERSION_servant_client */

/* package servant-client-core-0.16 */
#ifndef VERSION_servant_client_core
#define VERSION_servant_client_core "0.16"
#endif /* VERSION_servant_client_core */
#ifndef MIN_VERSION_servant_client_core
#define MIN_VERSION_servant_client_core(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  16 || \
  (major1) == 0 && (major2) == 16 && (minor) <= 0)
#endif /* MIN_VERSION_servant_client_core */

/* package servant-server-0.16.2 */
#ifndef VERSION_servant_server
#define VERSION_servant_server "0.16.2"
#endif /* VERSION_servant_server */
#ifndef MIN_VERSION_servant_server
#define MIN_VERSION_servant_server(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  16 || \
  (major1) == 0 && (major2) == 16 && (minor) <= 2)
#endif /* MIN_VERSION_servant_server */

/* package servant-swagger-1.1.7.1 */
#ifndef VERSION_servant_swagger
#define VERSION_servant_swagger "1.1.7.1"
#endif /* VERSION_servant_swagger */
#ifndef MIN_VERSION_servant_swagger
#define MIN_VERSION_servant_swagger(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 7)
#endif /* MIN_VERSION_servant_swagger */

/* package servant-swagger-ui-0.3.4.3.23.11 */
#ifndef VERSION_servant_swagger_ui
#define VERSION_servant_swagger_ui "0.3.4.3.23.11"
#endif /* VERSION_servant_swagger_ui */
#ifndef MIN_VERSION_servant_swagger_ui
#define MIN_VERSION_servant_swagger_ui(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_servant_swagger_ui */

/* package servant-swagger-ui-redoc-0.3.3.1.22.3 */
#ifndef VERSION_servant_swagger_ui_redoc
#define VERSION_servant_swagger_ui_redoc "0.3.3.1.22.3"
#endif /* VERSION_servant_swagger_ui_redoc */
#ifndef MIN_VERSION_servant_swagger_ui_redoc
#define MIN_VERSION_servant_swagger_ui_redoc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 3)
#endif /* MIN_VERSION_servant_swagger_ui_redoc */

/* package streaming-commons-0.2.1.2 */
#ifndef VERSION_streaming_commons
#define VERSION_streaming_commons "0.2.1.2"
#endif /* VERSION_streaming_commons */
#ifndef MIN_VERSION_streaming_commons
#define MIN_VERSION_streaming_commons(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_streaming_commons */

/* package swagger2-2.5 */
#ifndef VERSION_swagger2
#define VERSION_swagger2 "2.5"
#endif /* VERSION_swagger2 */
#ifndef MIN_VERSION_swagger2
#define MIN_VERSION_swagger2(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_swagger2 */

/* package text-1.2.4.0 */
#ifndef VERSION_text
#define VERSION_text "1.2.4.0"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_text */

/* package text-time-0.2.0 */
#ifndef VERSION_text_time
#define VERSION_text_time "0.2.0"
#endif /* VERSION_text_time */
#ifndef MIN_VERSION_text_time
#define MIN_VERSION_text_time(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_text_time */

/* package time-1.9.3 */
#ifndef VERSION_time
#define VERSION_time "1.9.3"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 3)
#endif /* MIN_VERSION_time */

/* package transformers-0.5.6.2 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.6.2"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_transformers */

/* package unliftio-0.2.12.1 */
#ifndef VERSION_unliftio
#define VERSION_unliftio "0.2.12.1"
#endif /* VERSION_unliftio */
#ifndef MIN_VERSION_unliftio
#define MIN_VERSION_unliftio(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 12)
#endif /* MIN_VERSION_unliftio */

/* package utf8-string-1.0.1.1 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.1.1"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_utf8_string */

/* package uuid-1.3.13 */
#ifndef VERSION_uuid
#define VERSION_uuid "1.3.13"
#endif /* VERSION_uuid */
#ifndef MIN_VERSION_uuid
#define MIN_VERSION_uuid(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 13)
#endif /* MIN_VERSION_uuid */

/* package uuid-types-1.0.3 */
#ifndef VERSION_uuid_types
#define VERSION_uuid_types "1.0.3"
#endif /* VERSION_uuid_types */
#ifndef MIN_VERSION_uuid_types
#define MIN_VERSION_uuid_types(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_VERSION_uuid_types */

/* package vault-0.3.1.4 */
#ifndef VERSION_vault
#define VERSION_vault "0.3.1.4"
#endif /* VERSION_vault */
#ifndef MIN_VERSION_vault
#define MIN_VERSION_vault(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_vault */

/* package vector-0.12.1.2 */
#ifndef VERSION_vector
#define VERSION_vector "0.12.1.2"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 1)
#endif /* MIN_VERSION_vector */

/* package wai-3.2.2.1 */
#ifndef VERSION_wai
#define VERSION_wai "3.2.2.1"
#endif /* VERSION_wai */
#ifndef MIN_VERSION_wai
#define MIN_VERSION_wai(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_wai */

/* package wai-cors-0.2.7 */
#ifndef VERSION_wai_cors
#define VERSION_wai_cors "0.2.7"
#endif /* VERSION_wai_cors */
#ifndef MIN_VERSION_wai_cors
#define MIN_VERSION_wai_cors(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 7)
#endif /* MIN_VERSION_wai_cors */

/* package wai-extra-3.0.29.1 */
#ifndef VERSION_wai_extra
#define VERSION_wai_extra "3.0.29.1"
#endif /* VERSION_wai_extra */
#ifndef MIN_VERSION_wai_extra
#define MIN_VERSION_wai_extra(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  0 || \
  (major1) == 3 && (major2) == 0 && (minor) <= 29)
#endif /* MIN_VERSION_wai_extra */

/* package wai-logger-2.3.6 */
#ifndef VERSION_wai_logger
#define VERSION_wai_logger "2.3.6"
#endif /* VERSION_wai_logger */
#ifndef MIN_VERSION_wai_logger
#define MIN_VERSION_wai_logger(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_wai_logger */

/* package warp-3.3.10 */
#ifndef VERSION_warp
#define VERSION_warp "3.3.10"
#endif /* VERSION_warp */
#ifndef MIN_VERSION_warp
#define MIN_VERSION_warp(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  3 || \
  (major1) == 3 && (major2) == 3 && (minor) <= 10)
#endif /* MIN_VERSION_warp */

/* package warp-tls-3.2.11 */
#ifndef VERSION_warp_tls
#define VERSION_warp_tls "3.2.11"
#endif /* VERSION_warp_tls */
#ifndef MIN_VERSION_warp_tls
#define MIN_VERSION_warp_tls(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 11)
#endif /* MIN_VERSION_warp_tls */

/* package word8-0.1.3 */
#ifndef VERSION_word8
#define VERSION_word8 "0.1.3"
#endif /* VERSION_word8 */
#ifndef MIN_VERSION_word8
#define MIN_VERSION_word8(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_word8 */

/* package world-peace-1.0.1.0 */
#ifndef VERSION_world_peace
#define VERSION_world_peace "1.0.1.0"
#endif /* VERSION_world_peace */
#ifndef MIN_VERSION_world_peace
#define MIN_VERSION_world_peace(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_world_peace */

/* package x509-1.7.5 */
#ifndef VERSION_x509
#define VERSION_x509 "1.7.5"
#endif /* VERSION_x509 */
#ifndef MIN_VERSION_x509
#define MIN_VERSION_x509(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  7 || \
  (major1) == 1 && (major2) == 7 && (minor) <= 5)
#endif /* MIN_VERSION_x509 */

/* package yaml-0.11.3.0 */
#ifndef VERSION_yaml
#define VERSION_yaml "0.11.3.0"
#endif /* VERSION_yaml */
#ifndef MIN_VERSION_yaml
#define MIN_VERSION_yaml(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 3)
#endif /* MIN_VERSION_yaml */

/* tool cpphs-1.20.9 */
#ifndef TOOL_VERSION_cpphs
#define TOOL_VERSION_cpphs "1.20.9"
#endif /* TOOL_VERSION_cpphs */
#ifndef MIN_TOOL_VERSION_cpphs
#define MIN_TOOL_VERSION_cpphs(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 9)
#endif /* MIN_TOOL_VERSION_cpphs */

/* tool doctest-0.16.3 */
#ifndef TOOL_VERSION_doctest
#define TOOL_VERSION_doctest "0.16.3"
#endif /* TOOL_VERSION_doctest */
#ifndef MIN_TOOL_VERSION_doctest
#define MIN_TOOL_VERSION_doctest(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  16 || \
  (major1) == 0 && (major2) == 16 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_doctest */

/* tool gcc-11.0.3 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "11.0.3"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  11 || \
  (major1) == 11 && (major2) <  0 || \
  (major1) == 11 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.8.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.8.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  8 || \
  (major1) == 8 && (major2) == 8 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.8.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.8.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  8 || \
  (major1) == 8 && (major2) == 8 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.23.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.23.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  23 || \
  (major1) == 2 && (major2) == 23 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool happy-1.19.12 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "1.19.12"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 12)
#endif /* MIN_TOOL_VERSION_happy */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.5 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.5"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool hscolour-1.24 */
#ifndef TOOL_VERSION_hscolour
#define TOOL_VERSION_hscolour "1.24"
#endif /* TOOL_VERSION_hscolour */
#ifndef MIN_TOOL_VERSION_hscolour
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  24 || \
  (major1) == 1 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hscolour */

/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.8.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.8.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  8 || \
  (major1) == 8 && (major2) == 8 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "fission-2.4.0-FAxds5BX2rA9fuOnd6FJrl"
#endif /* CURRENT_PACKAGE_KEY */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "fission-2.4.0-FAxds5BX2rA9fuOnd6FJrl"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "2.4.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
