jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 100
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    STACK_YAML: stack.yaml
    STACK_ROOT: /home/vsts/.stack
  steps:
    - task: CacheBeta@0
      inputs:
        key: |
          "cache"
          "version2"
          $(Agent.OS)
          $(Build.SourcesDirectory)/$(STACK_YAML)
        path: .azure-cache
        cacheHitVar: CACHE_RESTORED
      displayName: "Download cache"

    - bash: |
        mkdir -p $STACK_ROOT
        tar -xzf .azure-cache/stack-root.tar.gz -C /
        mkdir -p .stack-work
        tar -xzf .azure-cache/stack-work.tar.gz
      displayName: "Unpack cache"
      condition: eq(variables.CACHE_RESTORED, 'true')

    - bash: |
        mkdir -p ~/.local/bin
        curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      displayName: Install Stack

    - bash: |
        sudo apt-get update &&
        sudo apt-get -y install libpq-dev
      displayName: Install libpq-dev

    - bash: |
        export PATH=$HOME/.local/bin:$PATH
        stack --no-terminal --install-ghc build --copy-bins --local-bin-path $(Build.SourcesDirectory)
      displayName: Build Dependencies

    - bash: |
        export PATH=$HOME/.local/bin:$PATH
        make alltests
      displayName: Test ${{parameters.name}} Package

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: fission-cli-exe
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/${{ parameters.vmImage }}.zip'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifact: '${{ parameters.name }}'

    - bash: |
        mkdir -p .azure-cache
        tar -czf .azure-cache/stack-root.tar.gz $STACK_ROOT
        tar -czf .azure-cache/stack-work.tar.gz .stack-work
      displayName: "Pack cache"

    - task: GitHubRelease@0
      displayName: 'GitHub release (edit)'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        gitHubConnection: fission-cli-deploy
        repositoryName: '$(Build.Repository.Name)'
        action: edit
        tag: 'commit-$(Build.SourceVersion)'
        addChangeLog: true
        compareWith: lastFullRelease
        assets: '$(Build.ArtifactStagingDirectory)/${{ parameters.vmImage }}.zip'
        assetUploadMode: replace
        isDraft: true
