name: fission-cli
version: '2.9.0.0'
category: API
author:
  - Brooklyn Zelenka
  - Daniel Holmgren
  - Steven Vandevelde
maintainer:
  - brooklyn@fission.codes
  - daniel@fission.codes
  - steven@fission.codes
copyright: © 2020 Fission Internet Software Services for Open Networks Inc.
license: AGPL-3.0-or-later
license-file: LICENSE
github: fission-suite/fission
tested-with: GHC==8.8.3
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  # Warn about too little
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  # Warn about too much
  - -Wredundant-constraints
  # Prettier Development
  - -fhide-source-paths

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DuplicateRecordFields
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - LiberalTypeSynonyms
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NumericUnderscores
  - OverloadedStrings
  - OverloadedLabels
  - OverloadedLists
  - PostfixOperators
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - TypeOperators
  - ViewPatterns

dependencies:
  ## Base ##
  - base
  - rio
  - rio-orphans

  ## Capabilities ##
  - monad-logger
  - monad-time
  - mtl

  ## CLI ##
  - ansi-terminal
  - haskeline
  - optparse-applicative

  ## Concurrency & Parallelism ##
  - parallel

  ## Cryptogrpahy ##
  - cryptonite

  ## Data ##
  - aeson
  - bytestring
  - memory
  - utf8-string
  - yaml

  ## Error Handling ##
  - exceptions
  - rescue

  ## File System ##
  - file-embed
  - path-pieces
  - fsnotify

  ## Lenses ##
  - generic-lens

  ## Web ##
  - dns
  - http-client
  - http-client-tls
  - http-types
  - ipfs
  - servant
  - servant-client
  - servant-client-core

  ## Fission ##
  - fission-core

library:
  source-dirs: library

executables:
  fission:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - fission-cli
    ghc-options:
      - -threaded
      - -flate-specialise
      - -rtsopts
      - -with-rtsopts=-N
      - -with-rtsopts=-T
      - -optc-ffast-math
      - -optc-O3
      - -O2
    # uncomment to build a static binary on Linux
    # cc-options: -static
    # ld-options: -static -pthread

tests:
  fission-cli-doctest:
    main: Main.hs
    source-dirs: doctest
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - directory
      - directory-tree
      - doctest
      - fission-cli
      - fission-core
      - Glob
      - lens-aeson
      - QuickCheck
      - quickcheck-instances
      - servant-quickcheck
      - yaml

  fission-cli-test:
    main: Main.hs
    source-dirs:
      - library
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - hspec-core
      - hspec-expectations
      - hspec-wai
      - hspec-wai-json
      - fission-cli
      - fission-core
      - QuickCheck
      - quickcheck-instances
      - servant-quickcheck
      - tasty
      - tasty-hunit
      - tasty-hspec
      - tasty-smallcheck
      - tasty-rerun
      - transformers

#   fission-cli-lint:
#     main: Main.hs
#     source-dirs: lint
#     dependencies:
#       - base
#       - hlint
#       - rio

benchmarks:
  fission-cli-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - criterion
      - fission-cli
      - fission-core
